baseURL = 'https://blog.moyongxin.top/'
title = "qwertyuiop's blog"
enableGitInfo = true
pagination.pagerSize = 5
defaultContentLanguage = "zh"
comments = true

[markup.goldmark.parser.attribute]
block = true

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
noClasses = false

[module]
# In case you would like to make changes to the theme and keep it locally in you repository,
# uncomment the line below (and correct the local path if necessary).
# --
# replacements = "github.com/panr/hugo-theme-terminal/v4 -> themes/terminal"
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']
taxonomy = ['html', 'rss']

[caches]
[caches.images]
dir = ':cacheDir/images'
