languageName = "简体中文"
languageCode = 'zh-CN'

[params]
subtitle = "定义、创造与分享。"
owner = "moyongxin"
keywords = "计算机科学"
copyright = ""
menuMore = "显示更多"
readMore = "阅读更多"
readOtherPosts = "阅读其他文章"
newerPosts = "更新的文章"
olderPosts = "旧的文章"
missingContentMessage = "页面未找到..."
missingBackButtonLabel = "返回主页"
minuteReadingTime = "分钟阅读"
words = "词"
updatedDatePrefix = "更新于"
TocTitle = "目录"

[params.logo]
logoText = "qwertyuiop's blog"
logoHomeLink = "/"

[menu]
[[menu.main]]
identifier = "about"
name = "关于"
url = "/about"
[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags"
