languageName = "English"
languageCode = 'en'

[params]
subtitle = "Define, Create And Share."
owner = "moyongxin"
keywords = "Computer Science"
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"
updatedDatePrefix = "Updated"
TocTitle = "Table of Contents"

[params.logo]
logoText = "qwertyuiop's blog"
logoHomeLink = "/en"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/en/about"
[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/en/tags"
